Write programs in Python using NumPy library to do the following:

a. Compute the mean, standard deviation, and variance of a two dimensional random integer array
along the second axis.

b. Get the indices of the sorted elements of a given array.
    B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]

c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data
type of the array and then reshape it into nx m array, n and m are user inputs given at the run time.

d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of
these elements in three separate arrays.

In [15]:
#part-a

import numpy as np
data = np.random.randint(20,size=(4,5))
print(data)


#axis=1 will compute mean/std/var along each inner list i.e row
mean_data=np.mean(data,axis=1)
print("Mean :",mean_data)

standard_deviation=np.std(data,axis=1)
print("Standar Deviation is:",standard_deviation)

variance=np.var(data,axis=1)
print("Variance:",variance)



[[ 0 16  7 18 11]
 [17 18  3 19  6]
 [10 11 10  5  6]
 [ 3 12 11 10  5]]
Mean : [10.4 12.6  8.4  8.2]
Standar Deviation is: [6.46838465 6.71118469 2.41660919 3.54400903]
Variance: [41.84 45.04  5.84 12.56]


In [21]:
# part-b

array1=np.array([56, 48, 22, 41, 78, 91, 24, 46, 8, 33])

# argsort will sort the array
# and give index of element in array instead of its value.
sorted_array=np.argsort(array1)
print("Output sorted array indices :",sorted_array)

# We pass sorted index in original array (Fancy Indexing)
print("Output sorted array : ",array1[sorted_array])

Output sorted array indices : [8 2 6 9 3 7 1 0 4 5]
Output sorted array :  [ 8 22 24 33 41 46 48 56 78 91]


In [24]:
# part-c
import numpy as np
m=int(input("Enter n:"))
n=int(input("Enter m:"))
array1=np.zeros((m,n))

print(array1)
print("Shape:",array1.shape)
print("Data Type",array1.dtype)
print("Type:",type(array1))

print("Reshape array:")
print(array1.reshape(n,m)) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (5, 4)
Data Type float64
Type: <class 'numpy.ndarray'>
Reshape array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
# part d
import numpy as np

arr = np.array([0, 1, 2, np.nan, 3, 0, 4, np.nan, 5])
print("The array is:",arr)

zero = arr==0
nonzero = arr!=0
nan = np.isnan(arr)

print()
print("The elements that are zero are : ",zero)
print("The elements that are non-zero are : ",nonzero)
print("The elements that are NaN are : ",nan)

# where function return the indices of element which are true
zero_indices = np.where(arr)[0]
nonzero_indices = np.where(nonzero)[0]
nan_indices = np.where(nan)[0]

print()
print("The indices of the elements that are zero are : ",zero_indices)
print("The indices of the elements that are non-zero are : ",nonzero_indices)
print("The indices of the elements that are NaN are : ",nan_indices)


The array is: [ 0.  1.  2. nan  3.  0.  4. nan  5.]

The elements that are zero are :  [ True False False False False  True False False False]
The elements that are non-zero are :  [False  True  True  True  True False  True  True  True]
The elements that are NaN are :  [False False False  True False False False  True False]

The indices of the elements that are zero are :  [0 5]
The indices of the elements that are non-zero are :  [1 2 3 4 6 7 8]
The indices of the elements that are NaN are :  [3 7]
